---
- hosts: all
  tasks:
    - name: install prerequisites for node.js
      apt: pkg=python-software-properties,python,g++,make state=present
      sudo: true

    - name: add new apt repo with node.js available
      apt_repository: repo=ppa:chris-lea/node.js state=present
      sudo: true

    - name: apt-get update with new repo attached
      apt: update_cache=yes
      sudo: true

    - name: install node.js
      apt: pkg=nodejs state=present
      sudo: true

    - name: install git
      apt: pkg=git-core state=present
      sudo: true

    - name: clone DIRECT-node repo from GitHub
      git: repo=https://github.com/kachok/DIRECT-node.git dest={{repo_path}}

    - name: install all NPM packages required by DIRECT-node
      npm: path={{repo_path}}

    - name: override Node.js app settings.js
      template: src=files/settings.js dest={{repo_path}}/settings.js
      sudo: yes

    - name: install DNS as upstart service
      template: src=files/dns-direct.conf dest=/etc/init/dns-direct.conf
      sudo: yes
      notify:
        - restart DNS      

    - name: install SMTP as upstart service
      template: src=files/smtp-direct.conf dest=/etc/init/smtp-direct.conf
      sudo: yes
      notify:
        - restart SMTP      

    # need to restart DNS and SMTP based on code change (e.g. git task above)

  handlers:
    - name: restart DNS
      service:  name=dns-direct state=restarted
      sudo: yes

    - name: restart SMTP
      service:  name=smtp-direct state=restarted
      sudo: yes